#관리자 권한 갖기
sudo: required

#언어(플랫폼)을 선택
language: generic

#도커 환경 구성
service:
  - docker

#스크립트 실행 준비
before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t yongsookim/docker-react-app -f Dockerfile.dev .

#실행할 스크립트
script:
  - docker run -e CI=true yongsookim/docker-react-app npm run test -- --coverage

#테스트 성공후 로그 출력.
after_success:
  - echo "Test success"

# #Deploy
# deploy:
#   # 외부 서비스 표시(s3,elasticbeanstalk, firebase)
#   provider: elasticbeanstalk
#   # 현재 사용하고 있는 AWS의 서비스가 위치하고 있는 물리적 장소
#   region: "us-west-2"
#   # 생성된 어플리케이션의 이름
#   app: "docker-react-app"
#   env: "Dockerreactapp-env"
#   # 해당 elasticbeanstalk를 위한 s3버킷 이름.
#   bucket_name: "elasticbeanstalk-us-west-2-584310680275"
#   bucket_path: "docker-react-app"
#   on:
#     branch: master
  
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_ACCESS_KEY